#!/usr/bin/env python3
"""Render the finite row-2599 node-canary payload as Lean source.

The generated module is deliberately data-only.  The Lean checker in
``formal/lean/NineDVLFormal/NodeCanary.lean`` supplies all algorithms and
proofs, while this bridge makes its input byte-reproducible from the exact
JSON certificate.
"""

from __future__ import annotations

import argparse
from hashlib import sha256
import json
from pathlib import Path


HERE = Path(__file__).resolve().parent
DEFAULT_INPUT = HERE / "data" / "DIAG3_PAIR_MASTER_CLOSURE_NODE_CANARY.json"
DEFAULT_OUTPUT = (
    HERE.parent.parent
    / "formal"
    / "lean"
    / "NineDVLFormal"
    / "GeneratedNodeData.lean"
)

CELL_TO_SIMPLEX = {
    "v": [0],
    "p0": [1],
    "p1": [2],
    "p2": [3],
    "p3": [4],
    "w0": [0, 1],
    "w3": [0, 2],
    "w1": [0, 3],
    "w2": [0, 4],
    "b0": [1, 2],
    "b1": [2, 3],
    "b2": [3, 4],
    "b3": [1, 4],
    "c0": [0, 1, 2],
    "c1": [0, 2, 3],
    "c2": [0, 3, 4],
    "c3": [0, 1, 4],
}


def lean(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, int):
        return str(value)
    if isinstance(value, tuple):
        return "(" + ", ".join(lean(item) for item in value) + ")"
    if isinstance(value, list):
        return "[" + ", ".join(lean(item) for item in value) + "]"
    raise TypeError(type(value))


def incidence_matrix(boundary: dict, lower_key: str, upper_key: str, entries_key: str):
    lower = boundary[lower_key]
    upper = boundary[upper_key]
    entries = {(row, column): int(value) for row, column, value in boundary[entries_key]}
    return [[entries.get((row, column), 0) for column in upper] for row in lower]


def payload(record: dict, digest: str) -> dict:
    if record["format"] != "diag3-pair-master-closure-certificate-v1":
        raise ValueError("unexpected certificate format")
    if record["status"] != "LOCAL_EXACT_CANARY":
        raise ValueError("unexpected certificate status")

    cells = record["cells"]
    cell_ids = [cell["id"] for cell in cells]
    if len(cell_ids) != len(set(cell_ids)) or set(cell_ids) != set(CELL_TO_SIMPLEX):
        raise ValueError("unexpected cell identifier universe")

    scope = record["scope"]
    if scope["local_parameter_coverage"] != "COMPLETE":
        raise ValueError("unexpected local coverage claim")
    if scope["global_parameter_coverage"] != "NOT_CLAIMED":
        raise ValueError("unexpected global coverage claim")
    profiles = record["signature_profile_source"]["profiles"]
    boundary = record["integral_boundary"]
    return {
        "sourceFormat": record["format"],
        "sourceStatus": record["status"],
        "certificateSha256": digest,
        "formatVersion": 1,
        "parentIndex": int(scope["parent_index"]),
        "support": list(map(int, scope["support"])),
        "localCoverage": True,
        "globalCoverage": False,
        "masterCells": [CELL_TO_SIMPLEX[identifier] for identifier in cell_ids],
        "scopeBoundary": [CELL_TO_SIMPLEX[identifier] for identifier in record["scope_boundary_subcomplex"]],
        "parentInfinity": [CELL_TO_SIMPLEX[identifier] for identifier in record["parent_infinity_subcomplex"]],
        "profileCensus": [
            (int(row["feasible_chamber_mask"]), int(row["signature_count"]))
            for row in profiles
        ],
        "integralD1": incidence_matrix(boundary, "c0_basis", "c1_basis", "d1_entries"),
        "integralD2": incidence_matrix(boundary, "c1_basis", "c2_basis", "d2_entries"),
    }


def render(data: dict) -> str:
    return "\n".join(
        [
            "import Std",
            "",
            "/-! This file is generated by",
            "`python ai/omreal/build_diag3_pair_master_closure_node_lean.py`.",
            "Do not edit it by hand. -/",
            "",
            "namespace NineDVLFormal.GeneratedNodeData",
            "",
            "abbrev Simplex := List Nat",
            "abbrev IntMatrix := List (List Int)",
            "",
            f"def sourceFormat : String := {lean(data['sourceFormat'])}",
            f"def sourceStatus : String := {lean(data['sourceStatus'])}",
            f"def certificateSha256 : String := {lean(data['certificateSha256'])}",
            f"def formatVersion : Nat := {lean(data['formatVersion'])}",
            f"def parentIndex : Nat := {lean(data['parentIndex'])}",
            f"def support : List Nat := {lean(data['support'])}",
            f"def localCoverage : Bool := {lean(data['localCoverage'])}",
            f"def globalCoverage : Bool := {lean(data['globalCoverage'])}",
            f"def masterCells : List Simplex := {lean(data['masterCells'])}",
            f"def scopeBoundary : List Simplex := {lean(data['scopeBoundary'])}",
            f"def parentInfinity : List Simplex := {lean(data['parentInfinity'])}",
            f"def profileCensus : List (Nat × Nat) := {lean(data['profileCensus'])}",
            f"def integralD1 : IntMatrix := {lean(data['integralD1'])}",
            f"def integralD2 : IntMatrix := {lean(data['integralD2'])}",
            "",
            "end NineDVLFormal.GeneratedNodeData",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    source = args.input.read_bytes()
    expected = render(payload(json.loads(source), sha256(source).hexdigest()))
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != expected:
            raise SystemExit(f"stale generated Lean data: {args.output}")
        print("PASS generated Lean node data matches the JSON certificate")
        return

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8")
    print(args.output)


if __name__ == "__main__":
    main()
