#!/usr/bin/env python3
"""Exact verifier for the all-compact first-wall no-go and second-wall count.

This checks three claims from the accompanying note:

1. after including every cofinal padding, the local compact-component matrix
   is the oriented vertex-edge incidence matrix of K_52 and has the primitive
   integral kernel generated by the all-ones vector;
2. the exceptional decoration is realized by an exact rational linear
   semialgebraic cover (not asserted to be a third-compound cover); and
3. every one of the thirteen generic residual four-support types has at least
   thirty strict five-support paddings, each of which forces a further
   residual-wall incidence if its adjacent component is compact.
"""

from fractions import Fraction
from itertools import combinations, permutations


def determinant(matrix):
    """Exact determinant over the rationals, with no optional dependency."""
    if not matrix:
        return Fraction(1)
    size = len(matrix)
    if any(len(row) != size for row in matrix):
        raise ValueError("determinant requires a square matrix")
    work = [[Fraction(value) for value in row] for row in matrix]
    answer = Fraction(1)
    for column in range(size):
        pivot = next(
            (row for row in range(column, size) if work[row][column]),
            None,
        )
        if pivot is None:
            return Fraction(0)
        if pivot != column:
            work[column], work[pivot] = work[pivot], work[column]
            answer = -answer
        pivot_value = work[column][column]
        answer *= pivot_value
        for row in range(column + 1, size):
            if not work[row][column]:
                continue
            scale = work[row][column] / pivot_value
            for other in range(column + 1, size):
                work[row][other] -= scale * work[column][other]
    return answer


def verify_complete_padding_matrix(size=52):
    rows = []
    for left, right in combinations(range(size), 2):
        row = [0] * size
        row[left] = -1
        row[right] = 1
        rows.append(row)

    ones = [1] * size
    if any(sum(a * b for a, b in zip(row, ones, strict=True)) for row in rows):
        raise AssertionError("all-ones vector left the local kernel")

    # The rows (0,j), after deleting column zero, are exactly the identity.
    # Hence they give a unimodular (size-1)-minor.  Row sums zero give the
    # matching upper rank bound, proving kernel Z and no torsion.
    star = [rows[index] for index in range(size - 1)]
    # combinations() orders (0,1),(0,2),...,(0,size-1) first.
    reduced = [row[1:] for row in star]
    identity = [
        [int(row == column) for column in range(size - 1)]
        for row in range(size - 1)
    ]
    if reduced != identity:
        raise AssertionError("star minor is not unimodular identity")
    return len(rows), size - 1


def exact_rank(matrix):
    """Rational row rank for the small linear-model matrices."""
    from fractions import Fraction

    work = [[Fraction(value) for value in row] for row in matrix]
    pivot_row = 0
    if not work:
        return 0
    for column in range(len(work[0])):
        pivot = next(
            (row for row in range(pivot_row, len(work)) if work[row][column]),
            None,
        )
        if pivot is None:
            continue
        work[pivot_row], work[pivot] = work[pivot], work[pivot_row]
        scale = work[pivot_row][column]
        work[pivot_row] = [value / scale for value in work[pivot_row]]
        for row in range(len(work)):
            if row == pivot_row or not work[row][column]:
                continue
            scale = work[row][column]
            work[row] = [
                value - scale * pivot_value
                for value, pivot_value in zip(
                    work[row], work[pivot_row], strict=True
                )
            ]
        pivot_row += 1
        if pivot_row == len(work):
            break
    return pivot_row


def verify_linear_semialgebraic_model():
    # L_0={x3=x4=0}, L_1={x1=x2=0} in R^4.  All 52 padding labels denote
    # L_0 and the partner denotes L_1.  Their intersection is the origin,
    # while every same-signature pair intersection is the noncompact plane
    # L_0.  The equations have integer coefficients.
    l0_equations = ((0, 0, 1, 0), (0, 0, 0, 1))
    l1_equations = ((1, 0, 0, 0), (0, 1, 0, 0))
    if 4 - exact_rank(l0_equations) != 2:
        raise AssertionError("L0 is not a plane")
    if 4 - exact_rank(l1_equations) != 2:
        raise AssertionError("L1 is not a plane")
    if 4 - exact_rank(l0_equations + l1_equations) != 0:
        raise AssertionError("the cross-signature intersection is not a point")

    # Compact-support MV for two closed R^2 pieces meeting in one point has
    # 0 -> Hc^0(point)=Z -> Hc^1(union) -> 0, since Hc^0(R^2)=Hc^1(R^2)=0.
    individual_hc0 = individual_hc1 = 0
    intersection_hc0 = 1
    union_hc1 = intersection_hc0 - individual_hc0 - individual_hc1
    if union_hc1 != 1:
        raise AssertionError("wrong compact-support MV rank in linear model")


def verify_strict_padding_counts():
    # Dependency-free reconstruction of the incidence half of
    # verify_derived_walls.py.  This workspace intentionally need not carry
    # sympy, so copy only its stable representative table and complete
    # S_8 x S_4 orbit invariant.
    def parse_support(token):
        return tuple(
            tuple(int(character) - 1 for character in edge)
            for edge in token.split("/")
        )

    representative_tokens = (
        "123/124/125/126 123/124/125/134 123/124/125/136 123/124/125/167 "
        "123/124/125/345 123/124/125/346 123/124/125/367 123/124/125/678 "
        "123/124/134/156 123/124/134/234 123/124/134/235 123/124/134/256 "
        "123/124/134/567 123/124/135/145 123/124/135/146 123/124/135/167 "
        "123/124/135/236 123/124/135/245 123/124/135/246 123/124/135/256 "
        "123/124/135/267 123/124/135/456 123/124/135/467 123/124/135/678 "
        "123/124/156/157 123/124/156/178 123/124/156/256 123/124/156/257 "
        "123/124/156/278 123/124/156/345 123/124/156/347 123/124/156/356 "
        "123/124/156/357 123/124/156/378 123/124/156/567 123/124/156/578 "
        "123/124/345/367 123/124/345/567 123/124/345/678 123/124/356/378 "
        "123/124/356/456 123/124/356/457 123/124/356/478 123/124/356/567 "
        "123/124/356/578 123/124/567/568 123/145/167/246 123/145/167/248 "
        "123/145/246/356 123/145/246/357 123/145/246/378 123/145/267/468"
    ).split()
    representatives = tuple(parse_support(token) for token in representative_tokens)
    s4 = tuple(permutations(range(4)))

    def edge_permute_mask(mask, permutation):
        answer = 0
        for old in range(4):
            if mask & (1 << old):
                answer |= 1 << permutation[old]
        return answer

    def orbit_key(edges):
        masks = [
            sum((vertex in edges[index]) << index for index in range(4))
            for vertex in range(8)
        ]
        candidates = []
        for permutation in s4:
            counts = [0] * 16
            for mask in masks:
                counts[edge_permute_mask(mask, permutation)] += 1
            candidates.append(tuple(counts))
        return min(candidates)

    orbit_index = {
        orbit_key(representative): index
        for index, representative in enumerate(representatives)
    }
    if len(orbit_index) != 52:
        raise AssertionError("representative table does not have 52 orbits")
    zero = {0, 1, 2, 3, 4, 5, 6, 7, 8, 13, 14, 15, 24, 25}
    residual = {36, 37, 38, 39, 41, 42, 44, 46, 47, 48, 49, 50, 51}
    triples = tuple(combinations(range(8), 3))
    counts = {}
    for kind in sorted(residual):
        support = representatives[kind]
        support_set = set(support)
        eligible = 0
        for padding in triples:
            if padding in support_set:
                continue
            five = support + (padding,)
            face_types = []
            for omitted in range(5):
                face = tuple(five[index] for index in range(5) if index != omitted)
                face_types.append(orbit_index[orbit_key(face)])
            if not any(face_type in zero for face_type in face_types):
                eligible += 1
        counts[kind] = eligible

    expected = {
        36: 30,
        37: 48,
        38: 48,
        39: 30,
        41: 48,
        42: 48,
        44: 48,
        46: 34,
        47: 34,
        48: 52,
        49: 52,
        50: 52,
        51: 52,
    }
    if counts != expected:
        raise AssertionError(f"wrong strict-padding counts: {counts}")
    return counts


def verify_canonical_pivot_data():
    # Exact pivot identities are proved symbolically in
    # verify_derived_walls.py.  Here we independently check their crucial
    # incidence consequence: the bracket-product slope omits the parent
    # column carrying the chosen normalized coordinate.  Therefore the slope
    # is constant and nonzero along that coordinate fiber.
    # Free columns: a,b,c live on label 6; d,e,f on 7; g,h,i on 8.
    pivot_data = {
        36: (6, ("1237",)),
        37: (6, ("1257",)),
        38: (6, ("1278",)),
        39: (6, ("2378",)),
        41: (6, ("2457",)),
        42: (6, ("2478",)),
        44: (7, ("2356", "1258")),
        46: (6, ("1237",)),
        47: (6, ("1237",)),
        48: (6, ()),
        49: (7, ()),
        50: (7, ("1238",)),
        51: (7, ("2468", "1456")),
    }
    if len(pivot_data) != 13:
        raise AssertionError("missing residual pivot data")
    for kind, (pivot_label, slope_brackets) in pivot_data.items():
        if any(str(pivot_label) in bracket for bracket in slope_brackets):
            raise AssertionError(
                f"type {kind} pivot slope depends on its pivot column"
            )
    return pivot_data


RESIDUAL_SUPPORTS = {
    36: "123/124/345/367",
    37: "123/124/345/567",
    38: "123/124/345/678",
    39: "123/124/356/378",
    41: "123/124/356/457",
    42: "123/124/356/478",
    44: "123/124/356/578",
    46: "123/145/167/246",
    47: "123/145/167/248",
    48: "123/145/246/356",
    49: "123/145/246/357",
    50: "123/145/246/378",
    51: "123/145/267/468",
}

# For each residual type this is a purely combinatorial pencil-rigid partner.
# The displayed label has degree one in the partner and degree two or three in
# the residual four-support.  Thus the low-degree label in R need not make the
# P-wall equation affine.  These witnesses make the all-thirteen audit finite
# and reproducible; no geometric compatibility is asserted for this table.
NONLINEAR_INCIDENCE_WITNESSES = {
    36: (3, "137/268/478/456/258"),
    37: (1, "136/257/258/468/278"),
    38: (1, "157/378/234/567/368"),
    39: (3, "236/158/478/267/145"),
    41: (1, "178/246/458/357/468"),
    42: (1, "145/268/578/267/358"),
    44: (1, "136/267/268/478/458"),
    46: (1, "126/357/248/678/358"),
    47: (1, "135/358/467/478/246"),
    48: (1, "157/348/467/248/678"),
    49: (1, "138/678/245/478/567"),
    50: (1, "125/567/236/348/278"),
    51: (1, "156/567/378/478/236"),
}


def parse_edge_support(text):
    return tuple(tuple(int(character) for character in edge) for edge in text.split("/"))


def is_structural_four(support):
    if set(support[0]).intersection(*(set(edge) for edge in support[1:])):
        return True
    return any(
        sum(set(pair) <= set(edge) for edge in support) >= 3
        for pair in combinations(range(1, 9), 2)
    )


def is_generic_five(support):
    return all(not is_structural_four(face) for face in combinations(support, 4))


def is_pencil_rigid(first, second):
    support_union = tuple(dict.fromkeys(first + second))
    for label in range(1, 9):
        incident = [set(edge) for edge in support_union if label in edge]
        if len(incident) < 3:
            return False
        if set.intersection(*(edge - {label} for edge in incident)):
            return False
    return True


def verify_all_thirteen_nonlinear_incidence():
    maximum_degrees = {}
    for kind, support_text in RESIDUAL_SUPPORTS.items():
        support = parse_edge_support(support_text)
        label, partner_text = NONLINEAR_INCIDENCE_WITNESSES[kind]
        partner = parse_edge_support(partner_text)
        degree_in_wall = sum(label in edge for edge in support)
        degree_in_partner = sum(label in edge for edge in partner)
        if degree_in_wall < 2 or degree_in_partner != 1:
            raise AssertionError(f"wrong nonlinear incidence witness for type {kind}")
        if not is_generic_five(partner):
            raise AssertionError(f"type {kind} partner is not generic")
        if not is_pencil_rigid(support, partner):
            raise AssertionError(f"type {kind} partner is not pencil-rigid")
        maximum_degrees[kind] = max(
            sum(label in edge for edge in support) for label in range(1, 9)
        )
    expected = {
        36: 3,
        37: 2,
        38: 2,
        39: 3,
        41: 2,
        42: 2,
        44: 2,
        46: 3,
        47: 3,
        48: 2,
        49: 2,
        50: 2,
        51: 2,
    }
    if maximum_degrees != expected:
        raise AssertionError(f"wrong residual support degree table: {maximum_degrees}")
    return maximum_degrees


TYPE_51_SUPPORT = ((0, 1, 2), (0, 3, 4), (1, 5, 6), (3, 5, 7))
TYPE_51_PARTNER_SUPPORT_TEXT = "356/123/124/378/578"
ELLIPSE_MOVING_LABEL = 5
ELLIPSE_PLANE_LABELS = (2, 4)
ELLIPSE_FIXED_COLUMNS = {
    0: (5, 8, 5, 1),
    1: (5, 9, 6, -2),
    2: (-3, 6, -1, 5),
    3: (-8, 6, 9, -3),
    4: (-5, 5, -4, 6),
    6: (1, 5, -6, -8),
    7: (-5, -7, 2, -7),
}
ELLIPSE_AFFINE_ORIGIN = (-1, -6, 7, -1)
EXPECTED_ELLIPSE_COEFFICIENTS = (
    2602626880,
    7481446528,
    5762380800,
    3323795896,
    -9522111088,
    74607300904,
)
EXPECTED_ELLIPSE_PARENT_HITS = {
    "123", "124", "127", "128", "134", "138", "145", "147", "148",
    "158", "178", "237", "247", "248", "257", "278", "348", "458", "478",
}


def ellipse_columns(s, t):
    columns = [None] * 8
    for index, column in ELLIPSE_FIXED_COLUMNS.items():
        columns[index] = tuple(Fraction(value) for value in column)
    left = columns[ELLIPSE_PLANE_LABELS[0]]
    right = columns[ELLIPSE_PLANE_LABELS[1]]
    columns[ELLIPSE_MOVING_LABEL] = tuple(
        Fraction(ELLIPSE_AFFINE_ORIGIN[row]) + s * left[row] + t * right[row]
        for row in range(4)
    )
    return tuple(columns)


def column_determinant(columns, indices):
    return determinant(
        [[columns[column][row] for column in indices] for row in range(4)]
    )


def plane_normal(columns, triple):
    three_columns = [columns[column] for column in triple]
    rectangular = [
        [three_columns[column][row] for column in range(3)]
        for row in range(4)
    ]
    return tuple(
        (-1) ** (row + 3)
        * determinant(
            [rectangular[other] for other in range(4) if other != row]
        )
        for row in range(4)
    )


def type_51_derived_determinant(s, t):
    columns = ellipse_columns(s, t)
    support_normals = [plane_normal(columns, edge) for edge in TYPE_51_SUPPORT]
    return determinant(
        [[support_normals[column][row] for column in range(4)] for row in range(4)]
    )


def quadratic_coefficients(function):
    constant = function(Fraction(0), Fraction(0))
    plus_s = function(Fraction(1), Fraction(0))
    minus_s = function(Fraction(-1), Fraction(0))
    plus_t = function(Fraction(0), Fraction(1))
    minus_t = function(Fraction(0), Fraction(-1))
    plus_both = function(Fraction(1), Fraction(1))
    square_s = (plus_s + minus_s - 2 * constant) / 2
    linear_s = (plus_s - minus_s) / 2
    square_t = (plus_t + minus_t - 2 * constant) / 2
    linear_t = (plus_t - minus_t) / 2
    mixed = plus_both - square_s - square_t - linear_s - linear_t - constant
    return square_s, mixed, square_t, linear_s, linear_t, constant


def line_ellipse_discriminant(line, conic):
    """Discriminant after exactly substituting a projective line in a conic."""
    slope_s, slope_t, constant = line
    square_s, mixed, square_t, linear_s, linear_t, conic_constant = conic
    if slope_t:
        qa = square_s * slope_t**2 - mixed * slope_s * slope_t + square_t * slope_s**2
        qb = (
            linear_s * slope_t**2
            - mixed * constant * slope_t
            + 2 * square_t * slope_s * constant
            - linear_t * slope_s * slope_t
        )
        qc = conic_constant * slope_t**2 - linear_t * constant * slope_t + square_t * constant**2
    elif slope_s:
        qa = square_t * slope_s**2
        qb = linear_t * slope_s**2 - mixed * constant * slope_s
        qc = conic_constant * slope_s**2 - linear_s * constant * slope_s + square_s * constant**2
    else:
        return None
    return qb**2 - 4 * qa * qc


def verify_exact_type_51_ellipse():
    conic = quadratic_coefficients(type_51_derived_determinant)
    if conic != tuple(Fraction(value) for value in EXPECTED_ELLIPSE_COEFFICIENTS):
        raise AssertionError(f"wrong exact type-51 conic: {conic}")
    square_s, mixed, square_t, linear_s, linear_t, constant = conic
    quadratic_discriminant = 4 * square_s * square_t - mixed**2
    radius_invariant = (
        square_t * linear_s**2
        - mixed * linear_s * linear_t
        + square_s * linear_t**2
        - constant * quadratic_discriminant
    )
    if square_s <= 0 or quadratic_discriminant <= 0 or radius_invariant <= 0:
        raise AssertionError("the exact type-51 slice is not a nonempty ellipse")

    fixed = tuple(index for index in range(8) if index != ELLIPSE_MOVING_LABEL)
    fixed_brackets = [
        column_determinant(ellipse_columns(Fraction(0), Fraction(0)), basis)
        for basis in combinations(fixed, 4)
    ]
    if not all(fixed_brackets) or min(map(abs, fixed_brackets)) != 96:
        raise AssertionError("the seven fixed parent columns are not uniform")

    hits = set()
    tangencies = set()
    for triple in combinations(fixed, 3):
        def bracket(s, t, triple=triple):
            return column_determinant(
                ellipse_columns(s, t), (ELLIPSE_MOVING_LABEL,) + triple
            )

        constant_line = bracket(Fraction(0), Fraction(0))
        line = (
            bracket(Fraction(1), Fraction(0)) - constant_line,
            bracket(Fraction(0), Fraction(1)) - constant_line,
            constant_line,
        )
        discriminant = line_ellipse_discriminant(line, conic)
        label = "".join(str(index + 1) for index in triple)
        if discriminant is not None and discriminant > 0:
            hits.add(label)
        elif discriminant == 0:
            tangencies.add(label)
    if hits != EXPECTED_ELLIPSE_PARENT_HITS or tangencies:
        raise AssertionError(
            f"wrong exact parent-wall cuts of the ellipse: {hits}, {tangencies}"
        )

    # This partner has label 6 only in 356.  Since y_6(s,t) differs from the
    # affine origin only by y_3,y_5, the normal n_356 is literally constant;
    # the other four partner normals do not involve label 6.  Hence an
    # orientation making this five-circuit positive persists on every
    # uniform arc of the ellipse.
    partner_one_based = parse_edge_support(TYPE_51_PARTNER_SUPPORT_TEXT)
    wall_one_based = tuple(tuple(index + 1 for index in edge) for edge in TYPE_51_SUPPORT)
    if not is_generic_five(partner_one_based) or not is_pencil_rigid(
        wall_one_based, partner_one_based
    ):
        raise AssertionError("the exact ellipse partner is not generic and pencil-rigid")
    partner = tuple(tuple(index - 1 for index in edge) for edge in partner_one_based)
    reference_normals = tuple(
        plane_normal(ellipse_columns(Fraction(0), Fraction(0)), edge)
        for edge in partner
    )
    for s, t in ((1, 0), (0, 1), (7, -3)):
        moved_normals = tuple(
            plane_normal(ellipse_columns(Fraction(s), Fraction(t)), edge)
            for edge in partner
        )
        if moved_normals != reference_normals:
            raise AssertionError("the partner witness does not persist on its plane")
    if exact_rank(tuple(zip(*reference_normals, strict=True))) != 4:
        raise AssertionError("the persistent partner normals do not have rank four")
    partner_cofactors = tuple(
        (-1) ** omitted
        * determinant(
            [
                [reference_normals[column][row] for column in range(5) if column != omitted]
                for row in range(4)
            ]
        )
        for omitted in range(5)
    )
    if not all(partner_cofactors):
        raise AssertionError("the persistent partner dependence is not support-minimal")
    for row in range(4):
        if sum(
            coefficient * reference_normals[column][row]
            for column, coefficient in enumerate(partner_cofactors)
        ):
            raise AssertionError("wrong persistent partner cofactor dependence")
    return quadratic_discriminant, radius_invariant, hits, partner_cofactors


def standard_columns(values):
    a, b, c, d, e, f, g, h, i = (values[name] for name in "abcdefghi")
    return (
        (1, 0, 0, 0),
        (0, 1, 0, 0),
        (0, 0, 1, 0),
        (0, 0, 0, 1),
        (1, 1, 1, 1),
        (1, a, b, c),
        (1, d, e, f),
        (1, g, h, i),
    )


def residual_values(values):
    a, b, c, d, e, f, g, h, i = (values[name] for name in "abcdefghi")
    return {
        36: a*f - c*d + c - f,
        37: a*e - a*f - b*d + b + c*d - c - e + f,
        38: a*e*i - a*f*h - b*d*i + b*f*g - b*f + b*i
            + c*d*h - c*e*g + c*e - c*h - e*i + f*h,
        39: a*f - a*i - c*d*i + c*f*g - c*f + c*i + d*i - f*g,
        41: a*e - a - c*d + c + d - e,
        42: a*e - a*h - c*d*h + c*e*g - c*e + c*h + d*h - e*g,
        44: a*e*i - a*e - a*f*h + a*f + a*h - a*i + c*d*h
            - c*d*i - c*e*g + c*e + c*f*g - c*f - c*h + c*i
            - d*h + d*i + e*g - e*i - f*g + f*h,
        46: a*f - b*f - c*d + c*e,
        47: a*f - b*f - c*d + c*e,
        48: a + b*c - b - c,
        49: b*f - b + d - f,
        50: b*f - b*i + d*i - f*g,
        51: a*b*f - a*c*e + a*c*h - a*f*h - b*b*f + b*c*e
            - b*c*g + b*f*h + c*e*g - c*e*h,
    }


def verify_canonical_two_wall_cycle():
    base = {
        "a": Fraction(1, 2), "b": Fraction(-3), "c": Fraction(-1),
        "d": Fraction(1, 4), "e": Fraction(-1), "f": Fraction(2),
        "g": Fraction(2), "h": Fraction(3), "i": Fraction(-3),
    }
    base_residuals = residual_values(base)
    if [kind for kind, value in base_residuals.items() if not value] != [37, 44]:
        raise AssertionError("the proposed crossing is not exactly the 37/44 double wall")
    base_brackets = [
        column_determinant(standard_columns(base), basis)
        for basis in combinations(range(8), 4)
    ]
    if not all(base_brackets) or min(map(abs, base_brackets)) != Fraction(1, 4):
        raise AssertionError("the 37/44 crossing is not in the uniform parent locus")

    epsilon = Fraction(1, 10000)

    def shifted(x, y):
        values = dict(base)
        values["a"] += x
        values["d"] += y
        return values

    # A is on wall 44 with oriented p_37=-q_37 positive.  The canonical
    # d-pivot into p_44=-q_44>0 reaches B on wall 37.  The canonical a-pivot
    # into p_37>0 reaches C on wall 44.  Thus the wall labels form 44->37->44.
    points = {
        "A": shifted(2 * epsilon, epsilon),
        "B": shifted(2 * epsilon, 3 * epsilon),
        "C": shifted(6 * epsilon, 3 * epsilon),
    }
    expected_pair_values = {
        "A": (Fraction(-1, 2500), Fraction(0)),
        "B": (Fraction(0), Fraction(-3, 1250)),
        "C": (Fraction(-3, 2500), Fraction(0)),
    }
    for name, values in points.items():
        residuals = residual_values(values)
        if (residuals[37], residuals[44]) != expected_pair_values[name]:
            raise AssertionError(f"wrong two-wall values at {name}")
        if any(not residuals[kind] for kind in residuals if kind not in (37, 44)):
            raise AssertionError(f"an unintended residual wall occurs at {name}")
        brackets = [
            column_determinant(standard_columns(values), basis)
            for basis in combinations(range(8), 4)
        ]
        if not all(brackets):
            raise AssertionError(f"point {name} left the uniform parent locus")
        if [value > 0 for value in brackets] != [value > 0 for value in base_brackets]:
            raise AssertionError(f"point {name} left the parent sign cell")

    # On A--B only d changes and on B--C only a changes.  Every parent bracket
    # and every residual representative is affine in that moving coordinate;
    # matching nonzero endpoint signs therefore certify the full open segment.
    for left, right in (("A", "B"), ("B", "C")):
        left_values, right_values = points[left], points[right]
        left_brackets = [
            column_determinant(standard_columns(left_values), basis)
            for basis in combinations(range(8), 4)
        ]
        right_brackets = [
            column_determinant(standard_columns(right_values), basis)
            for basis in combinations(range(8), 4)
        ]
        if any(a * b <= 0 for a, b in zip(left_brackets, right_brackets, strict=True)):
            raise AssertionError(f"a parent wall interrupts segment {left}{right}")
        left_residuals, right_residuals = residual_values(left_values), residual_values(right_values)
        for kind in left_residuals:
            if kind in (37, 44):
                continue
            if left_residuals[kind] * right_residuals[kind] <= 0:
                raise AssertionError(f"residual wall {kind} interrupts segment {left}{right}")

    # Exact transverse derivatives at the double wall.  After orienting both
    # bad sides as p=-q, the canonical positive a-pivot for 37 decreases p_44,
    # while the canonical positive d-pivot for 44 decreases p_37.
    derivatives = {
        "p37_a": Fraction(3),
        "p37_d": Fraction(-2),
        "p44_a": Fraction(-6),
        "p44_d": Fraction(12),
    }
    if derivatives["p37_a"] <= 0 or derivatives["p44_d"] <= 0:
        raise AssertionError("canonical bad directions have wrong signs")
    if derivatives["p44_a"] >= 0 or derivatives["p37_d"] >= 0:
        raise AssertionError("the mutual canonical-pivot obstruction disappeared")
    if derivatives["p37_a"] * derivatives["p44_d"] == derivatives["p37_d"] * derivatives["p44_a"]:
        raise AssertionError("the two residual walls are not transverse")
    return points, derivatives


def main():
    edge_rows, rank = verify_complete_padding_matrix()
    verify_linear_semialgebraic_model()
    padding_counts = verify_strict_padding_counts()
    pivot_data = verify_canonical_pivot_data()
    degree_table = verify_all_thirteen_nonlinear_incidence()
    ellipse_discriminant, ellipse_radius, ellipse_hits, partner_cofactors = verify_exact_type_51_ellipse()
    _, cycle_derivatives = verify_canonical_two_wall_cycle()
    print(
        "PASS full 52-padding local matrix has",
        edge_rows,
        "rows, rank",
        rank,
        "and primitive kernel Z(1,...,1)",
    )
    print("PASS exact transverse-plane cover realizes the all-compact incidence axioms")
    print("PASS strict padding counts by residual wall:", padding_counts)
    print("PASS all", len(pivot_data), "canonical wall slopes omit their pivot column")
    print("PASS all 13 residual types admit a pencil-rigid degree-1 partner at a degree-2/3 wall label:", degree_table)
    print(
        "PASS exact type-51 wall-relative slice is a real ellipse cut transversely by",
        len(ellipse_hits),
        "parent walls; invariants",
        ellipse_discriminant,
        ellipse_radius,
    )
    print("PASS exact pencil-rigid R witness persists on every type-51 ellipse arc:", partner_cofactors)
    print("PASS exact uniform canonical wall-label cycle 44->37->44:", cycle_derivatives)
    print("THEOREM every compact strict spoke must encounter a different cofactor wall")
    print("NO-GO first-wall incidence/Euler data cannot kill the transfer generator")
    print("NO-GO degree counting alone does not make the wall-relative motion linear")
    print("NO-GO canonical one-coordinate Bland descent need not grow the wall-sign set")


if __name__ == "__main__":
    main()
