#!/usr/bin/env python3
"""Exact component-decorated d1 graph at the parent-16 pivot wall.

This builds the smallest Cech wall star generated by the positive four-
circuit P=124/134/235/567, its 52 cofinal five-support paddings, and the
strict partner R=126/247/158/468/378.

The formal incidence matrix has 51 rows, one for each third support T != Q.
After support-only pencil pruning it has a one-dimensional transfer kernel.
The exact component decoration removes that kernel: the central Q,R component
through the wall is noncompact by a concatenated certified escape, while all
Q,T components are pencil-flexible.  Any compact R,T component through the
wall therefore has a private triple-component row with coefficient +/-1.
The resulting 51-by-51 matrix is invertible over Z.

The script also verifies that the signed sparse four-circuit/partner tensor
pair has only the scalar projective infinitesimal stabilizer.  Hence the local
injectivity is genuinely supplied by component incidence, not by a hidden
one-parameter tensor flow.

This is a local theorem at one exact wall.  It does not prove diagonal two.
"""

from pathlib import Path
import sys


HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import DIAG2_PIVOT_VERIFY as pivot  # noqa: E402
import prototype_koszul_circuits as koszul  # noqa: E402
import verify_beta0_mixed_escape as beta  # noqa: E402
import verify_second_diagonal_defect_two as defect  # noqa: E402


LEFT_TAG = 0
RIGHT_TAG = 1


def piece(tag, support):
    return tag, tuple(sorted(support))


Q = piece(LEFT_TAG, defect.LEFT_SUPPORT)
R = piece(RIGHT_TAG, defect.RIGHT_SUPPORT)
DROPPED = koszul.TRIPLE_INDEX[pivot.DROPPED_TRIPLE]
P = tuple(index for index in defect.LEFT_SUPPORT if index != DROPPED)
PADDINGS = tuple(
    piece(LEFT_TAG, P + (candidate,))
    for candidate in range(len(koszul.TRIPLES))
    if candidate not in P
)
ALTERNATIVE_PADDINGS = tuple(item for item in PADDINGS if item != Q)


def pair(first, second):
    return tuple(sorted((first, second)))


def cech_row(first, second, third):
    """Return the signed pair boundary of an ordered three-piece simplex."""
    vertices = tuple(sorted((first, second, third)))
    return {
        pair(vertices[1], vertices[2]): 1,
        pair(vertices[0], vertices[2]): -1,
        pair(vertices[0], vertices[1]): 1,
    }


def matrix_rank_integer(matrix):
    return pivot.rational_rank(matrix)


def incidence_matrix(rows, columns):
    position = {column: index for index, column in enumerate(columns)}
    matrix = []
    for row in rows:
        values = [0] * len(columns)
        for column, coefficient in row.items():
            if column in position:
                values[position[column]] = coefficient
        matrix.append(values)
    return matrix


def degrees(support_union):
    return tuple(
        sum(label in koszul.TRIPLES[index] for index in support_union)
        for label in range(1, 9)
    )


def verify_wall_star_ranks():
    if len(PADDINGS) != 52 or len(ALTERNATIVE_PADDINGS) != 51:
        raise AssertionError("wrong cofinal padding count")

    rows = [cech_row(Q, R, current) for current in ALTERNATIVE_PADDINGS]
    central = pair(Q, R)
    qt_columns = [pair(Q, current) for current in ALTERNATIVE_PADDINGS]
    rt_columns = [pair(R, current) for current in ALTERNATIVE_PADDINGS]

    # Before any pruning there are 103 formal pair columns.  Every row is an
    # ordinary oriented triangle boundary, so the 51 rows are independent but
    # the formal kernel has dimension 52.
    formal_columns = [central] + qt_columns + rt_columns
    formal_matrix = incidence_matrix(rows, formal_columns)
    formal_rank = matrix_rank_integer(formal_matrix)
    if formal_rank != 51 or len(formal_columns) - formal_rank != 52:
        raise AssertionError("wrong formal wall-star ranks")

    # Q and T share the four-support P, so Q union T has at most six triples.
    # Incidence counting gives a degree-at-most-two label in every case; the
    # projective-plane-pencil lemma removes all 51 Q,T compact-component
    # columns.  The remaining support-only star has one transfer kernel.
    for current in ALTERNATIVE_PADDINGS:
        support_union = set(Q[1]) | set(current[1])
        if len(support_union) > 6 or min(degrees(support_union)) > 2:
            raise AssertionError("a Q,T pair is not pencil-flexible")
    support_columns = [central] + rt_columns
    support_matrix = incidence_matrix(rows, support_columns)
    support_rank = matrix_rank_integer(support_matrix)
    if support_rank != 51 or len(support_columns) - support_rank != 1:
        raise AssertionError("wrong support-pruned transfer kernel")

    # The exact escape removes the central Q,R compact-component column.  Each
    # remaining row then has exactly its own R,T column with coefficient +/-1,
    # so the component-decorated matrix is unimodular diagonal up to row/column
    # signs and permutation.
    component_matrix = incidence_matrix(rows, rt_columns)
    component_rank = matrix_rank_integer(component_matrix)
    if component_rank != 51:
        raise AssertionError("the component-decorated wall matrix is singular")
    if any(sum(value != 0 for value in row) != 1 for row in component_matrix):
        raise AssertionError("a decorated row is not private")
    if any(
        sum(component_matrix[row][column] != 0 for row in range(51)) != 1
        for column in range(51)
    ):
        raise AssertionError("a decorated column has more than one pivot row")
    determinant = 1
    for row in component_matrix:
        determinant *= next(value for value in row if value)
    if abs(determinant) != 1:
        raise AssertionError("the decorated wall matrix is not unimodular")
    return formal_rank, support_rank, component_rank


def support_signs(signature, support):
    return tuple(
        1 if (signature >> koszul.TRIPLE_INDEX[triple]) & 1 else -1
        for triple in support
    )


def verify_scalar_only_stabilizer():
    four_support = tuple(koszul.TRIPLES[index] for index in P)
    partner_support = tuple(koszul.TRIPLES[index] for index in defect.RIGHT_SUPPORT)
    gauge = beta.gauge_matrix(four_support, partner_support)
    if len(gauge) != 7 or beta.rational_rank(gauge) != 7:
        raise AssertionError("the wall tensor pair is not beta zero")

    tensors = (
        beta.signed_tensor(
            four_support, support_signs(defect.LEFT_SIGNATURE, four_support)
        ),
        beta.signed_tensor(
            partner_support,
            support_signs(defect.RIGHT_SIGNATURE, partner_support),
        ),
    )
    # There are 64 entries of A and two block eigenvalues.  Modular rank 65
    # is a rational lower bound.  The scalar solution gives a rational
    # nullvector, hence rational rank <=65, proving exact rank 65 and nullity 1.
    equation_rank = beta.projective_stabilizer_rank(tensors)
    if equation_rank != 65:
        raise AssertionError("the wall tensor pair has a non-scalar stabilizer")


def verify_component_decorations():
    # The first segment Y(t), 0<=t<=t*, preserves Q and R and reaches the
    # four-circuit wall.  The second stored segment from Y(0) to [1678]=0
    # preserves Q and R.  Their concatenation proves that the Q,R component
    # containing the wall point is noncompact.
    left_orientation, right_orientation, dropped_index = pivot.exact_first_pivot()
    if dropped_index != defect.LEFT_SUPPORT.index(DROPPED):
        raise AssertionError("the wrong support drops at the wall")
    pivot.verify_padding_fan(left_orientation, right_orientation, dropped_index)
    defect.verify_escape()

    # Properness and incomparability are inherited from the exact child
    # certificates; they are not needed for the local matrix rank but ensure
    # this is an actual 9DVL-qualified pair rather than an abstract support.
    pivot.verify_proper_incomparable_hypotheses()


def main():
    verify_component_decorations()
    formal_rank, support_rank, component_rank = verify_wall_star_ranks()
    verify_scalar_only_stabilizer()
    print("PASS all 52 cofinal paddings and 51 distinct triple rows are enumerated")
    print(f"PASS formal wall star: rank {formal_rank}, kernel dimension 52")
    print(f"PASS support-pruned star: rank {support_rank}, transfer kernel dimension 1")
    print(f"PASS component-decorated star: rank {component_rank}, kernel dimension 0")
    print("PASS central Q,R wall component has an exact concatenated boundary escape")
    print("PASS all Q,T competitors are removed by degree-at-most-two pencil escape")
    print("PASS wall tensor pair is beta=0 with scalar-only projective stabilizer")
    print("THEOREM no local d1 cycle survives through this exact defect-two wall")
    print("CAVEAT this is one wall component, not a universal proof of diagonal two")


if __name__ == "__main__":
    main()
