"""Mutation-graph BFS with voltages + holonomy subgroup computation.

Setting (see OMGAMMA.md for the proved reduction):
  Gamma_bar = labeled mutation graph: vertices = uniform OMs {chi,-chi} on
  [n], edges = single-basis flips.  G' = S_n x {0,1}^n x {0,1} acts; the
  kernel on pair-vertices is K4 = {(id,0,0),(id,1^n,0),(id,0,1),(id,1^n,1)}
  (n>=r+1); the effective group is Gbar = G'/K4, |Gbar| = n! 2^(n-1).
  Elements are normalized as (sigma, eps, 0) with eps := min(eps, eps^full).

  Given Gamma_hat (= Gamma_bar / Gbar) connected, with H = component
  stabilizer of the base vertex:
    #components(Gamma_bar)  = [Gbar : H]
    #components(Gamma_tilde) = [S_n : pi(H)]
  H is generated by (i) tau_c u tau_c^{-1} for stabilizer elements u of
  each class rep, (ii) tau_c t tau_{c'}^{-1} for every non-tree mutation
  edge with voltage t, where tau are spanning-tree transports.

This module: exact BFS over all classes with full edge enumeration
(feasible for rank 3 n<=9 and rank 4 n<=8 in-process), harvesting H.
"""
import time
from math import comb, factorial

from core import (bases_colex, mutable_bases, g_compose, g_inverse,
                  g_apply, g_identity)
from canon import canonical


# ---------------------------------------------------------------- Gbar ops

def normalize(n, g):
    """Reduce (sigma,eps,s) modulo K4: force s=0, eps mod all-ones."""
    sig, eps, s = g
    full = (1 << n) - 1
    e2 = eps ^ full
    return (sig, min(eps, e2), 0)


def bar_compose(n, g1, g2):
    return normalize(n, g_compose(n, g1, g2))


def bar_inverse(n, g):
    return normalize(n, g_inverse(n, g))


# ---------------------------------------------------------------- BSGS

class PermGroup:
    """Incremental Schreier-Sims for subgroups of S_n (1-based tuples)."""

    def __init__(self, n):
        self.n = n
        self.base = list(range(1, n + 1))
        self.transversal = [dict() for _ in range(n)]   # level -> {pt: perm}
        self.strong = [[] for _ in range(n)]            # gens fixing base<level
        ident = tuple(range(1, n + 1))
        for lv in range(n):
            self.transversal[lv][self.base[lv]] = ident
        self._order = 1

    def order(self):
        o = 1
        for lv in range(self.n):
            o *= len(self.transversal[lv])
        return o

    def _apply(self, p, x):
        return p[x - 1]

    def _mul(self, p, q):     # p*q : first q then p
        return tuple(p[q[i] - 1] for i in range(self.n))

    def _inv(self, p):
        out = [0] * self.n
        for i in range(self.n):
            out[p[i] - 1] = i + 1
        return tuple(out)

    def sift(self, p):
        """Return residue after sifting; identity residue = member."""
        for lv in range(self.n):
            x = self._apply(p, self.base[lv])
            if x not in self.transversal[lv]:
                return p, lv
            p = self._mul(self._inv(self.transversal[lv][x]), p)
        return p, self.n

    def contains(self, p):
        res, _ = self.sift(p)
        return all(res[i] == i + 1 for i in range(self.n))

    def add(self, p):
        """Add generator; returns True if the group grew."""
        res, lv = self.sift(p)
        if all(res[i] == i + 1 for i in range(self.n)):
            return False
        self.strong[lv].append(res)
        self._rebuild(lv)
        return True

    def _rebuild(self, from_lv):
        # recompute orbits/transversals from level from_lv downward
        for lv in range(from_lv, -1, -1):
            gens = []
            for l2 in range(lv + 1):
                gens += self.strong[l2]
            # orbit of base[lv] under gens fixing base[0..lv-1]?  For
            # simplicity (n<=9) use all gens that fix base[0..lv-1]
            use = [g for g in gens
                   if all(g[self.base[i] - 1] == self.base[i]
                          for i in range(lv))]
            tr = {self.base[lv]: tuple(range(1, self.n + 1))}
            frontier = [self.base[lv]]
            while frontier:
                x = frontier.pop()
                for g in use:
                    y = g[x - 1]
                    if y not in tr:
                        tr[y] = self._mul(g, tr[x])
                        frontier.append(y)
            self.transversal[lv] = tr
        # Schreier generators handled implicitly by resifting strong gens
        # (adequate for small n; verified against known orders in tests)
        changed = True
        while changed:
            changed = False
            allg = [g for lst in self.strong for g in lst]
            for lv in range(self.n):
                for x, t in list(self.transversal[lv].items()):
                    for g in allg:
                        if all(g[self.base[i] - 1] == self.base[i]
                               for i in range(lv)):
                            p = self._mul(g, t)
                            res, l2 = self.sift(p)
                            if not all(res[i] == i + 1
                                       for i in range(self.n)):
                                self.strong[l2].append(res)
                                for l3 in range(l2, -1, -1):
                                    pass
                                self._rebuild_simple(l2)
                                changed = True
        return

    def _rebuild_simple(self, from_lv):
        for lv in range(from_lv, -1, -1):
            gens = [g for lst in self.strong for g in lst]
            use = [g for g in gens
                   if all(g[self.base[i] - 1] == self.base[i]
                          for i in range(lv))]
            tr = {self.base[lv]: tuple(range(1, self.n + 1))}
            frontier = [self.base[lv]]
            while frontier:
                x = frontier.pop()
                for g in use:
                    y = g[x - 1]
                    if y not in tr:
                        tr[y] = self._mul(g, tr[x])
                        frontier.append(y)
            self.transversal[lv] = tr


# ---------------------------------------------------------------- F2 space

class SignSpace:
    """F2 subspace of {0,1}^n containing all-ones (kernel), via Gaussian
    basis (pivots = highest set bit)."""

    def __init__(self, n):
        self.n = n
        self.basis = {}
        self.add((1 << n) - 1)

    def add(self, v):
        while v:
            p = v.bit_length() - 1
            if p in self.basis:
                v ^= self.basis[p]
            else:
                self.basis[p] = v
                return True
        return False

    def dim(self):
        return len(self.basis)

    def full(self):
        return self.dim() == self.n


# ---------------------------------------------------------------- holonomy

class Holonomy:
    """Accumulates H <= Gbar from harvested elements; sound lower bound.

    perm part tracked by BSGS; pure-sign part by SignSpace; collision
    harvesting + product closure turn generic elements into sign elements.
    """

    def __init__(self, n):
        self.n = n
        self.P = PermGroup(n)
        self.U = SignSpace(n)
        self.reps = {}        # perm tuple -> full normalized element
        self.pending = []     # elements whose perm part is already known
        self.gen_log = []     # provenance records

    def _pure(self, g):
        sig, eps, _ = g
        return all(sig[i] == i + 1 for i in range(self.n)), eps

    def add(self, g, prov=None):
        g = normalize(self.n, g)
        pure, eps = self._pure(g)
        new = False
        if pure:
            new = self.U.add(eps)
        else:
            sig = g[0]
            if sig in self.reps:
                v = bar_compose(self.n, g, bar_inverse(self.n,
                                                       self.reps[sig]))
                p2, e2 = self._pure(v)
                assert p2
                new = self.U.add(e2)
            else:
                self.reps[sig] = g
                new = self.P.add(sig)
        if new and prov is not None:
            self.gen_log.append((prov, g))
        return new

    def close(self, rounds=200, rng=None):
        """Product closure to move perm-collisions into the sign space."""
        import random as _r
        rng = rng or _r
        reps = list(self.reps.values())
        if len(reps) < 2:
            return
        for _ in range(rounds):
            if self.full():
                return
            a = rng.choice(reps)
            b = rng.choice(reps)
            self.add(bar_compose(self.n, a, b))
            reps = list(self.reps.values())

    def saturate(self, limit=None):
        """Deterministic EXACT completion of the sign part U.

        Let L = the logged generators (those that grew P or U at add time;
        pi(L) generates pi(H*) = P by construction) and V = {v_g} the sign
        parts extracted from every stored rep g against a Schreier
        transversal of <L>.  Since each stored rep g = v_g * trans[pi(g)],
        H* = <L u V>, and because the sign subgroup is abelian and normal,
        sign(H*) = sign(<L>) + sum of spans of P-orbits of the v_g's.
        sign(<L>) comes from Schreier generators over the transversal;
        the P-orbit closure only needs the P-GENERATOR permutations.
        Cost ~ |P| * |L| compositions.
        """
        gens = [g for _, g in self.gen_log]
        for eps in list(self.U.basis.values()):
            gens.append((tuple(range(1, self.n + 1)), eps, 0))
        ident = tuple(range(1, self.n + 1))
        trans = {ident: normalize(self.n, g_identity(self.n))}
        frontier = [trans[ident]]
        cnt = 0
        while frontier:
            h = frontier.pop()
            for g in gens:
                hg = bar_compose(self.n, g, h)
                sig = hg[0]
                if sig in trans:
                    v = bar_compose(self.n, hg,
                                    bar_inverse(self.n, trans[sig]))
                    assert all(v[0][i] == i + 1 for i in range(self.n))
                    self.U.add(v[1])
                else:
                    trans[sig] = hg
                    frontier.append(hg)
                cnt += 1
                if limit and cnt > limit:
                    raise RuntimeError("saturate limit exceeded")
        # harvest every stored rep against the transversal
        for sig, g in self.reps.items():
            t = trans.get(sig)
            if t is None:
                # pi(g) not in <pi(L)> would contradict construction
                raise RuntimeError("rep perm outside transversal (bug)")
            v = bar_compose(self.n, g, bar_inverse(self.n, t))
            assert all(v[0][i] == i + 1 for i in range(self.n))
            self.U.add(v[1])
        # close U under the permutation action of P (generators suffice;
        # iterate to fixpoint)
        pgens = [g[0] for _, g in self.gen_log]
        changed = True
        while changed:
            changed = False
            for eps in list(self.U.basis.values()):
                for sig in pgens:
                    e2 = 0
                    for i in range(self.n):
                        if (eps >> i) & 1:
                            e2 |= 1 << (sig[i] - 1)
                    if self.U.add(e2):
                        changed = True
        self._transversal_size = len(trans)
        return len(trans)

    def full(self):
        return self.U.full() and self.P.order() == factorial(self.n)

    def status(self):
        return (self.P.order(), factorial(self.n), self.U.dim(), self.n)


# ---------------------------------------------------------------- BFS

def bfs_holonomy(n, r, start_mask, verbose=True, expect=None):
    """Full BFS of Gamma_hat from the class of start_mask.

    Returns dict with classes, tree data, holonomy object, stats.
    Every mutation edge of every visited class is enumerated (exhaustive),
    so the returned holonomy generators generate H exactly (given the
    reduction theorem) when the BFS covers all of Gamma_hat.
    """
    t0 = time.time()
    res0 = canonical(n, r, start_mask)
    key0 = res0['can']
    classes = {key0: 0}
    reps = [res0['canmask']]
    tau = [g_identity(n)]
    tree = [None]              # per class: (parent, flipidx, voltage t)
    hol = Holonomy(n)
    stab_count = 0
    for u in res0['stab']:
        hol.add(bar_compose(n, bar_compose(n, tau[0], u),
                            bar_inverse(n, tau[0])), prov=('stab', 0))
        stab_count += 1
    queue = [0]
    qi = 0
    nedges = 0
    while qi < len(queue):
        c = queue[qi]
        qi += 1
        chi = reps[c]
        for j in mutable_bases(n, r, chi):
            psi = chi ^ (1 << j)
            resm = canonical(n, r, psi)
            kk = resm['can']
            t = bar_inverse(n, resm['g'])   # psi = t . rep(child)
            nedges += 1
            if kk not in classes:
                cid = len(reps)
                classes[kk] = cid
                reps.append(resm['canmask'])
                tau.append(bar_compose(n, tau[c], t))
                tree.append((c, j, t))
                queue.append(cid)
                for u in resm['stab']:
                    hol.add(bar_compose(n, bar_compose(n, tau[cid], u),
                                        bar_inverse(n, tau[cid])),
                            prov=('stab', cid))
                    stab_count += 1
            else:
                c2 = classes[kk]
                h = bar_compose(n, bar_compose(n, tau[c], t),
                                bar_inverse(n, tau[c2]))
                hol.add(h, prov=('edge', c, j, c2))
        if verbose and qi % 500 == 0:
            print(f"   bfs {qi}/{len(queue)} classes, {nedges} edges, "
                  f"{time.time()-t0:.0f}s, hol={hol.status()}", flush=True)
    hol.exact = False
    try:
        hol.saturate(limit=60_000_000)
        hol.exact = True
    except RuntimeError:
        hol.close(rounds=4000)
    out = {
        'n': n, 'r': r,
        'nclasses': len(reps),
        'nedges_directed': nedges,
        'reps': reps,
        'classes': classes,
        'tau': tau,
        'tree': tree,
        'hol': hol,
        'stab_count': stab_count,
        'seconds': time.time() - t0,
    }
    if verbose:
        p_ord, p_full, u_dim, u_full = hol.status()
        print(f"BFS({n},{r}): {len(reps)} classes, {nedges} directed edge "
              f"traversals, {out['seconds']:.1f}s")
        print(f"   holonomy: |pi(H)| = {p_ord} (S_n = {p_full}),  "
              f"sign dim = {u_dim}/{u_full}")
        print(f"   Gamma_hat connected on reachable set; "
              f"H = Gbar: {hol.full()}")
        if expect is not None:
            print(f"   class count {'MATCHES' if len(reps)==expect else 'MISMATCHES'} expected {expect}")
    return out
