import Std

/-! This file is generated by
`python ai/omreal/build_diag3_pair_master_closure_node_lean.py`.
Do not edit it by hand. -/

namespace NineDVLFormal.GeneratedNodeData

abbrev Simplex := List Nat
abbrev IntMatrix := List (List Int)

def sourceFormat : String := "diag3-pair-master-closure-certificate-v1"
def sourceStatus : String := "LOCAL_EXACT_CANARY"
def certificateSha256 : String := "0f387e769568c236c0712f2514f7c28bbcc4fa82a417d6eaa56656976617b2b9"
def formatVersion : Nat := 1
def parentIndex : Nat := 2599
def support : List Nat := [15, 15, 15]
def localCoverage : Bool := true
def globalCoverage : Bool := false
def masterCells : List Simplex := [[0], [1], [2], [3], [4], [0, 1], [0, 2], [0, 3], [0, 4], [1, 2], [2, 3], [3, 4], [1, 4], [0, 1, 2], [0, 2, 3], [0, 3, 4], [0, 1, 4]]
def scopeBoundary : List Simplex := [[1], [2], [3], [4], [1, 2], [2, 3], [3, 4], [1, 4]]
def parentInfinity : List Simplex := []
def profileCensus : List (Nat × Nat) := [(0, 70968), (3, 72), (6, 72), (9, 72), (12, 72), (15, 25968)]
def integralD1 : IntMatrix := [[-1, -1, -1, -1, 0, 0, 0, 0], [1, 0, 0, 0, -1, 0, 0, 1], [0, 1, 0, 0, 1, -1, 0, 0], [0, 0, 1, 0, 0, 1, -1, 0], [0, 0, 0, 1, 0, 0, 1, -1]]
def integralD2 : IntMatrix := [[1, 0, 0, -1], [-1, 1, 0, 0], [0, -1, 1, 0], [0, 0, -1, 1], [1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]

end NineDVLFormal.GeneratedNodeData
